### ISSUE TITLE
NNpack questions

### ISSUE THREAD

**Issue by bookerb6** [shizukachan/darknet-nnpack#2]
First of all, great work. This application is faster on a PI 3. I would like to use it but have a few questions. Please note that I have never used c++, but not afraid to get my hands dirty.

1;) In the documentation you say that subsequent frames take less time than the first frame. May you please elaborate how can that be achieved because it seems like the weights are loaded from the file every time.

2.) I would like to make an addon so that I can use it in my node application. May you please advice on how to proceed. **Not** on making the addon, but ways to ensure that the application is not always loaded and advice in general to make it run smooth. I think just on making a simple main.cpp where I can call and use the relevant functions.

3.) There are alot of outputs but most will not be needed for my task. Which file sshould I look at if I just want to return a json/object/whatever with all the information (name, percenatge, x, y, width ...) and remove all the other information.

Thank you and great work.

**Comment by bookerb6** [comment]
*EDIT, I am only going to use images

**Comment by shizukachan** [comment]
In examples/detector.c, if filename isn't set, Darknet will loop infinitely if you feed in a filename from stdin+carriage return. Each entered image will return a set of predictions, and with the code in this repo, only the first prediction will be slower than the rest.

As for bounding boxes, there is some [cool stuff](https://github.com/DT42/BerryNet/blob/master/patch/01-detection-backend.patch) in BerryNet's repo where they patch Darknet's code to return bounding boxes.

I'm not sure if they keep Darknet open between sending images, but if they aren't, they are losing a huge amount of performance.

**Comment by bookerb6** [comment]
Thanks, I figured out most of the stuff.
"In the documentation you say that subsequent frames take less time than the first frame". What do you mean and how can I achieve that.

**Comment by bookerb6** [comment]
Just a side note, I am going to supply the images as either OPENCV MAT or buffers.

**Comment by bookerb6** [comment]
I have a stream of mjpeg which I process with my node application (around 6fps). I then want to supply the images to the darknet for detection. Currently I am using opencv (I made a opencv addon ) but the problem with that is alot of false positives, no matter how I try to tune it.

**Comment by shizukachan** [comment]
a) the first inference takes extra long to calculate because we have to compute the transformed kernel. later times we reuse the computation and it runs faster than the other code
b) write your own code that links against Darknet
c) Darknet is not going to be able to inference at 6fps

**Comment by bookerb6** [comment]
Need some help, it might be silly but never really used C/C++. I just replaced darknet.c with darknet.cpp. I am having trouble adding it to the makefile. Mind lending a hand.

**Comment by bookerb6** [comment]
Nothing?

**Comment by shizukachan** [comment]
Well, if your project was open source and interesting enough for me to consider working on it, I might consider donating my time, but it isn't...
